# The URL the site will be built for
base_url = "https://example.com"
title = "PROOF Workbench"
description = "Submit, track, and troubleshoot your WDL workflows on the FH cluster"
default_language = "en"
compile_sass = true
build_search_index = false

[markdown.highlighting]
style = "inline"
theme = "github-dark"

[extra]
navbar_links = [
  { title = "OCDO", url = "https://ocdo.fredhutch.org", external = true },
]
